# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ec2-user/aws-fpga/hdk/cl/examples/cl_hello_world_hlx/example_projects/cl_hello_world.srcs/sources_1/ip/square_root_with_reset/square_root_with_reset.xci
# IP: The module: 'square_root_with_reset' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ec2-user/aws-fpga/hdk/cl/examples/cl_hello_world_hlx/example_projects/cl_hello_world.gen/sources_1/ip/square_root_with_reset/square_root_with_reset_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'square_root_with_reset'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/ec2-user/aws-fpga/hdk/cl/examples/cl_hello_world_hlx/example_projects/cl_hello_world.srcs/sources_1/ip/square_root_with_reset/square_root_with_reset.xci
# IP: The module: 'square_root_with_reset' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ec2-user/aws-fpga/hdk/cl/examples/cl_hello_world_hlx/example_projects/cl_hello_world.gen/sources_1/ip/square_root_with_reset/square_root_with_reset_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'square_root_with_reset'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
